* OO abstraction
** OO: five characteristics
*** everything is an /object/
    you can model, in theory, any problem using objects. /objects store data/, and could be /requested to do some operation/ on their data 

*** a program is just a /bunch of objects/
    you can construct a program by using /multiple objects/ which tell each other what to do by /sending messages between to each other/

*** objects has their *own memory*
    every /new-kind object/ is is made up of other objects so you can hide the complexity of a certain program using objects, which make large programs looks simple

*** every object has a type
    typically, an object is just an instance of a /class/. one of the class characteristics is telling /which messages can a certain object send/.

*** objects of the /same type/ can *receive* the /same messages/
    a ~Dog~  is also an ~Animal~ so we can send a message to a ~Dog~ object to tell it to ~Eat()~

** class abstraction
   the OO programming is about creating new data types; objects. all the OO programming languages use the keyword ~class~ as it refers to /type/, adn vice versa.

   a class describes a set of /objects/ that have *identical* charactirictis -- =data members= and behaviors -- =functionality=. the programming system take care of the new class as it's a built-in class
 
   a class determine the /object interface/; what request you could establish to an instance of this class. the class must have a /function/ associates with each possible request 
   
** hiding the implementations
   the main goal of hiding the class implementation is to offer to the programmer only what's necessary and hide everything else. this protocol is to ensure that the programmer does not use so that the class creator can change the implementation without affecting having an impact on the programmer source code. /the concept of implementation hiding cannot be over-emphasized/.

   when you create a class you have ensure that the users, indeed programmer, shouldn't touch parts that are internal mechanisms which are not a part of the interface; thus internal/private partes.

** reusing units of code
*** reusing the implemetation
    this can be achieve by creating a member object of class A inside class B.
in theory, class B can have as much as member object as it needs to. this concept is called /composition/ or /aggregation/ 

*** reusing the interface
    this is often referred as /inheritance/ which is the act of reusing all the data members and functionality that exists in the base-class, /although teh private ones/, in a addition to new ones to construct a new class, derived-class. 

    all the messages that the base class can receive, could be received from the derived class too. and since the messages determine the type, thus the /base class and the derived class has the same type/

    beside the fact that the derived-class could add a new interface in addition to the base-interface which stay untouched, the base-interface could be overridden; keeping the same interface but only adjust it to the new type

* OO programming approach: Analysis and design
  so the methodology to create a program in OO is to answer to questions:

  + what are the objects
  + what are their interfaces
